### PR TITLE
Add ASmap run 1724248800

### PR DESCRIPTION
**Pull request by jurraca**
This adds the asmap.dat result for the coordinated launch from https://github.com/fjahr/asmap-data/issues/15 from the epoch 1724248800. We had a match from 6 out of 7 participants in the coordinated launch.

To confirm the result of the encoding you can use [asmap-tool](https://github.com/bitcoin/bitcoin/tree/master/contrib/asmap).

```
$ shasum -a 256 1724248800_final_result.txt
0236b4f8c6e023e3bd201996c49f9f10852be0ca7e5952a4ba26fc1c00b71153  1724248800_final_result.txt

$ python3 contrib/asmap/asmap-tool.py encode 1724248800_final_result.txt 1724248800_asmap.dat

$ shasum -a 256 1724248800_asmap.dat
dafaf52c1acd6e3f1e1e91d613c5fbbf7e9905e020ecfe101e381ce1a88dd84d 1724248800_asmap.dat
```

### CODE REVIEW

**Comment by fjahr** [comment]
> To confirm the result of the encoding you also need to check out https://github.com/bitcoin/bitcoin/pull/28793 to get the latest version of asmap-tool.

That PR was merged so you can now just link to the repository.

**Comment by fjahr** [comment]
ACK

I have received the same hash: `dafaf52c1acd6e3f1e1e91d613c5fbbf7e9905e020ecfe101e381ce1a88dd84d`.

```
$ shasum -a 256 1724248800-final_result.txt
0236b4f8c6e023e3bd201996c49f9f10852be0ca7e5952a4ba26fc1c00b71153  1724248800-final_result.txt
$ python3 contrib/asmap/asmap-tool.py encode 1724248800-final_result.txt 1724248800_asmap.dat
$ shasum -a 256 1724248800_asmap.dat
dafaf52c1acd6e3f1e1e91d613c5fbbf7e9905e020ecfe101e381ce1a88dd84d  1724248800_asmap.dat
```

To other reviewers that see this for the first time: This also edits a `latest_asmap.dat` file. It is just a copy of the timestamped file. We added this so there is a permanent (download) link to the latest asmap file that can be linked to in the [seeder README](https://github.com/bitcoin/bitcoin/pull/30008/files#diff-9468810859a6881caa4f5c4d3c806f494e8e078c4a4c9c53d8ed74a6d96d4973) and other places. There is a CI action that checks the hash of the latest asmap file (by timestamp) and the `latest_asmap.dat` file are equivalent: https://github.com/fjahr/asmap-data/blob/main/.github/workflows/latest_asmap.yml

**Review by brunoerg — APPROVED** [review]
ACK 8ff14e50c0a25ef3e77a5b2ff16f7298e5c5b4fd 🚀

```
$ shasum -a 256 final_result.txt
0236b4f8c6e023e3bd201996c49f9f10852be0ca7e5952a4ba26fc1c00b71153
$ python3 contrib/asmap/asmap-tool.py encode /projects/kartograf/out/1724248800/final_result.txt 1724248800_asmap.dat && shasum -a 256 1724248800_asmap.dat
dafaf52c1acd6e3f1e1e91d613c5fbbf7e9905e020ecfe101e381ce1a88dd84d  1724248800_asmap.dat
```

**Comment by Emzy** [comment]
ACK
```
$ sha256sum 1724248800_asmap.dat 
dafaf52c1acd6e3f1e1e91d613c5fbbf7e9905e020ecfe101e381ce1a88dd84d  1724248800_asmap.dat
```

**Comment by Sjors** [comment]
Post merge ACK, will try running this on my node as well.

**Pull request merged**
