### PR TITLE
Demo with kartograf 0.2.3: 1699394720

### PR DESCRIPTION
**Pull request by fjahr**
The data here is using RPKI and Routeviews to produce a demo asmap file for the purpose of testing reproducibility across systems and time.

Please get the latest version of kartograf (at least 0.2.3) and run:
```
./run map -r /path/to/this/repo/1699394720 -t 1699394720
```

This should result in a final result file with the hash `4cba5e3a865d7bcca903c40880420027fb7d55651a18e43f19fad848a6b33406`.

Be aware that the process takes ~6h on a 2020 Macbook Pro.

### CODE REVIEW

**Comment by Sjors** [comment]
On Ubuntu 23.04 I installed [fjahr/kartograph](https://github.com/fjahr/kartograf) master@3014b82a2d0d83312a3b9309256ffa1c065ff4c4 (not to be confused with [OpenFreeEnergy/kartograf](https://github.com/OpenFreeEnergy/kartograf)

Now running the above command...

**Comment by Sjors** [comment]
Well that ended quickly:

```
$ ./run map -r ../asmap-data/1699394720 -t 1699394720

--- Start Kartograf ---

The epoch for this run is: 1699394720 (2023-11-07 22:05:20 UTC, local: 2023-11-07 23:05:20 CET
This is a reproduction run based on the data in ../asmap-data/1699394720/

--- Validating RPKI ---

Validating RPKI ROAs
98289 raw RKPI DB entries downloaded and saved to /home/sjors/dev/kartograf/out/r1699394720/rpki/rpki_raw.json
...finished in 0:02:40.375330

--- Parsing RPKI ---

Parsing 0 ROAs
Output: 0
Duplicates: 0
Invalids: 0
Incompletes: 0
...finished in 0:00:00.000145

--- Parsing Routeviews pfx2as ---

Bogon filtered: 100.65.6.0/24
Bogon filtered: 100.65.7.0/24
Bogon filtered: 100.65.8.0/24
Bogon filtered: 100.65.10.0/24
Bogon filtered: 100.65.11.0/24
Bogon filtered: 100.65.13.0/24
Bogon filtered: 100.65.16.0/23
Bogon filtered: 100.66.3.0/24
Bogon filtered: 100.66.7.0/24
Bogon filtered: 100.66.9.0/24
Bogon filtered: 100.66.10.0/24
Bogon filtered: 100.70.8.0/24
Bogon filtered: 100.70.9.0/24
Bogon filtered: 100.70.16.0/24
Bogon filtered: 100.70.18.0/24
Bogon filtered: 100.70.20.0/24
Bogon filtered: 100.70.22.0/24
Bogon filtered: 100.70.24.0/24
Bogon filtered: 100.70.26.0/24
Bogon filtered: 100.70.28.0/24
Bogon filtered: 100.70.30.0/24
Bogon filtered: 100.70.44.0/24
Bogon filtered: 100.70.47.0/24
Bogon filtered: 100.70.50.0/24
Bogon filtered: 100.70.52.0/24
Bogon filtered: 100.70.59.0/24
Bogon filtered: 100.70.65.0/24
Bogon filtered: 100.70.104.0/24
Bogon filtered: 100.70.106.0/24
Bogon filtered: 100.70.108.0/24
Bogon filtered: 100.70.140.0/22
Bogon filtered: 100.70.243.0/24
Bogon filtered: 100.96.100.0/24
Bogon filtered: 100.127.8.0/23
Bogon filtered: 192.31.196.0/24
Bogon filtered: 192.175.48.0/24
Bogon filtered: 2001::/32
Bogon filtered: 2001:4:112::/48
Bogon filtered: 2002::/16
Bogon filtered: 2620:4f:8000::/48
...finished in 0:02:18.439555

--- Merging Routeviews and base data ---

Parse base file to numpy arrays
Parse extra file to Pandas DataFrame
Filtering extra prefixes that were already included in the base file
  0%|                                                                                                            | 1/1183115 [00:00<2:27:33, 133.63it/s]
Traceback (most recent call last):
  File "/home/sjors/dev/kartograf/./run", line 86, in <module>
    Kartograf.map(args)
  File "/home/sjors/dev/kartograf/kartograf/kartograf.py", line 69, in map
    merge_pfx2as(context)
  File "/home/sjors/dev/kartograf/kartograf/timed.py", line 10, in wrapper
    result = func(*args, **kwargs)
  File "/home/sjors/dev/kartograf/kartograf/merge.py", line 35, in merge_pfx2as
    general_merge(base_file, rv_file, rv_filtered_file, out_file)
  File "/home/sjors/dev/kartograf/kartograf/merge.py", line 85, in general_merge
    df_extra['INCLUDED'] = df_extra.INETS.progress_apply(check_inclusion)
  File "/home/sjors/.pyenv/versions/3.10.10/lib/python3.10/site-packages/tqdm/std.py", line 814, in inner
    return getattr(df, df_function)(wrapper, **kwargs)
  File "/home/sjors/.pyenv/versions/3.10.10/lib/python3.10/site-packages/pandas/core/series.py", line 4771, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/home/sjors/.pyenv/versions/3.10.10/lib/python3.10/site-packages/pandas/core/apply.py", line 1123, in apply
    return self.apply_standard()
  File "/home/sjors/.pyenv/versions/3.10.10/lib/python3.10/site-packages/pandas/core/apply.py", line 1174, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2924, in pandas._libs.lib.map_infer
  File "/home/sjors/.pyenv/versions/3.10.10/lib/python3.10/site-packages/tqdm/std.py", line 809, in wrapper
    return func(*args, **kwargs)
  File "/home/sjors/dev/kartograf/kartograf/merge.py", line 76, in check_inclusion
    inclusion_list = int(extra_net) & net_masks == network_addresses
TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

**Comment by Sjors** [comment]
Some extra info: `rpki-client-portable 8.2`

I ran an earlier version of this script on the same machine in September. I did run a `git clean -dfx` on this repo before trying this PR, but didn't clean any other caches.

**Comment by Sjors** [comment]
Updated Ubuntu and Kartograf to 8.5. Running again...

**Comment by Sjors** [comment]
Took about 4.5 hours. Different hash though…

```
--- Validating RPKI ---

Validating RPKI ROAs
c98289 raw RKPI DB entries downloaded and saved to /home/sjors/dev/kartograf/out/r1699394720/rpki/rpki_raw.json
...finished in 1:01:49.240574

--- Parsing RPKI ---

Parsing 98289 ROAs
Output: 352920
Duplicates: 33828
Invalids: 3579
Incompletes: 0
...finished in 0:00:42.274760

--- Parsing Routeviews pfx2as ---

Bogon filtered: 100.65.6.0/24
...
Bogon filtered: 2620:4f:8000::/48
...finished in 0:02:21.241519

--- Merging Routeviews and base data ---

Parse base file to numpy arrays
Parse extra file to Pandas DataFrame
Filtering extra prefixes that were already included in the base file
100%|██████████████████████████████████████████████████████████████████████████████████████| 1183115/1183115 [3:09:39<00:00, 103.97it/s]
Finished filtering! Originally 1183115 entries filtered down to 711395
Merging base file with filtered extra file
...finished in 3:09:46.119446

--- Sorting results ---

...finished in 0:00:06.132383

--- Finishing Kartograf ---

The SHA-256 hash of the result file is: b05544ac1247108e9e3dde0e9dae0bfb3e4052743bb7fc02bf3dfbfe0b8a8118
Total runtime: 4:14:45.025770
```

**Comment by fjahr** [comment]
@Sjors Hm, the logs look good. I used rpki-client 8.6 with this run, I will run with 8.5 to see if that changes the hash for me as well.

**Comment by fjahr** [comment]
@Sjors nope, that wasn't it, I still get the same hash as before with rpki-client 8.5 on my system. I guess we should just nixify everything, but I would really like to find out where the issue lies first. I will check which version I get on an Ubuntu box. Would you mind sharing your python version as well?

**Comment by Sjors** [comment]
Python 3.10.10

**Comment by fjahr** [comment]
@Sjors Ok, I think we got it now 😅 If you could test one more time with the latest Kartograf (0.2.3) that would be great! The new result hash is `4cba5e3a865d7bcca903c40880420027fb7d55651a18e43f19fad848a6b33406`. Tested on Ubuntu and Python 3.10, among others.

What happened is, that the file ordering coming from `pathlib` was different in Ubuntu and that led to different content in some cases because there can be multiple rpki roas for a single prefix and I chose to keep the first seen as a final tiebreaker which means file order could influence the result. Now we take the entry with the lower ASN as the final tiebreaker if validity etc are all equal.

**Comment by Sjors** [comment]
@fjahr you may want to tag the releases, but I'll try with the latest master f549ba1cb78525661354cd54aa08936e4ded84d4

**Comment by Sjors** [comment]
I like the progress indicator…

And I get the same hash! 🎉

**Comment by fjahr** [comment]
@Sjors Thanks a lot for sticking with me for this :)

I am working on some performance upgrades now and will motivate more people to test the process.

**Comment by fjahr** [comment]
I am closing this now in favor of the new demo using coordinated launch: https://github.com/fjahr/asmap-data/issues/4

@Sjors  it would awesome to see you join that demo! Instructions are in the issue.

**Pull request closed without merging**
